[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ENVIRONMENT = "production"
ADDITIONAL_CORS_ORIGINS = "https://lol-draft.netlify.app,https://develop--lol-draft.netlify.app" 