[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ENVIRONMENT = "production"
ADDITIONAL_CORS_ORIGINS = "https://lol-draft.netlify.app,https://develop--lol-draft.netlify.app"
PORT = "8000" 